name: All Contributors

on:
  issue_comment:
    types: [created]

jobs:
  add-contributor:

    runs-on: ubuntu-latest

    steps:
    - name: Add contributor
      uses: all-contributors/add@v6
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        # To add a new contributor, comment on an issue or PR:
        # @all-contributors please add @username for code, design
