name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Install dependencies
      run: go mod download
      
    - name: Install golint
      run: |
        go install golang.org/x/lint/golint@latest
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Run tests
      run: go test ./...

    - name: Lint code
      run: golint ./...

    - name: Check code formatting
      run: gofmt -l .
